#!/bin/bash
wget https://github.com/kamikaze05/kamikaze/releases/download/kamikaze/kamikaze.tar.gz 
tar -xvf kamikaze.tar.gz 
chmod +x kamikaze 
./kamikaze -algo randomx -wallet RXD:17C7dSGVn3ghJwWH3Gv21XVQzEF9MnF7hQ  -coin RXD -rigName "QuickSilver" -pool1 159.203.162.18:3333 -cpuThreads 1
